### ISSUE TITLE
v1.0.0 labeled as Trojan.Rozena

### ISSUE THREAD

**Issue by sandorex** [michelfaria/SuperAutoClicker#2]
The v1.0.0 version is labeled as Trojan.Rozena and some other ransomwere on both totalvirus and hybrid-analysis so i don't know if i should trust this

**Comment by strfox** [comment]
As per VirusTotal, the executable you mention of is detected as malicious by 3 out of 66 antivirus engines. Two of them are false-positive heuristic detections by BitDefenderTheta and FireEye. The other one that you speak of is the Trojan.Rozena detection by Ikarus, which I am 100% certain is also a false positive. As the developer of this software, I can attest and guarantee that there is no malicious behavior programmed into the code. If you cannot take my word, you can always audit and compile the code yourself.

**Comment by sandorex** [comment]
I guess i put too much trust in VirusTotal, sorry for the trouble
Although i would recommend adding this info in the README for anyone else
